<?php
// ============================================================
// SkyWave Travel - Configuration File
// Generated by Install Wizard
// ============================================================

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'your_database');
define('DB_USER', 'your_username');
define('DB_PASS', 'your_password');
define('DB_CHARSET', 'utf8mb4');

// Site URL (no trailing slash)
define('SITE_URL', 'http://yourdomain.com');

// File Paths
define('ROOT_PATH', dirname(__DIR__) . '/');
define('UPLOAD_PATH', ROOT_PATH . 'uploads/');
define('UPLOAD_URL', SITE_URL . '/uploads/');

// Session
define('SESSION_NAME', 'skywave_sess');

// App Version
define('APP_VERSION', '1.0.0');
?>
